---

- name: Delete EC2 key pair
  ec2_key:
    name: "{{ ec2_key_name }}"
    region: "{{ ec2_region }}"
    state: absent

- name: Delete the EC2 private key
  file:
    path: "{{ ec2_private_key_file }}"
    state: absent
