---

- name: Delete EC2 instances
  ec2:
    region: "{{ ec2_region }}"
    exact_count: 0
    count_tag:
      WorkshopName: "{{ workshop_name }}"
    wait: yes
    image: "{{ ec2_ami_id[ec2_region].ami }}"  # Required parameter for module, but not needed for deleting
