---

aws_access_key: your_access_key
aws_secret_key: your_secret_key

ec2_region: us-east-1
ec2_vpc_id: vpc-123456789
ec2_vpc_subnet_id: subnet-987654321

route53_hosted_zone: example.com

workshop_uid: acme
num_students: 10

rhsm_username: johndoe
rhsm_password: password123
rhsm_pool: 4a5b8de7d4c4fa3fd667b223e4468ff4
